### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by Like-h** [rationalspark/JTFT#1]
Traceback (most recent call last):
  File "/home/lkh/Project/code/JTFT-master/run_longExp.py", line 169, in <module>
    exp = Exp(args)  # set experiments
  File "/home/lkh/Project/code/JTFT-master/exp/exp_main.py", line 24, in __init__
    super(Exp_Main, self).__init__(args)
  File "/home/lkh/Project/code/JTFT-master/exp/exp_basic.py", line 13, in __init__
    self.model = torch.compile(self.model) #, mode="max-autotune"
AttributeError: module 'torch' has no attribute 'compile'

请问应该怎么修正呢

**Comment by rationalspark** [comment]
这个是因为pytorch版本低，好像2.0以上才能编译。不编译，把这个地方删了就行



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月06日 16:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [rationalspark/JTFT] 运行问题 (Issue #1) |

Traceback (most recent call last):
File "/home/lkh/Project/code/JTFT-master/run_longExp.py", line 169, in
exp = Exp(args) # set experiments
File "/home/lkh/Project/code/JTFT-master/exp/exp_main.py", line 24, in init
super(Exp_Main, self).init(args)
File "/home/lkh/Project/code/JTFT-master/exp/exp_basic.py", line 13, in init
self.model = torch.compile(self.model) #, mode="max-autotune"
AttributeError: module 'torch' has no attribute 'compile'

请问应该怎么修正呢
